Import numpy as np

In [1]:
import numpy as np


Make a python list => [1,2,3,4,5]

Convert it into numpy array and print it

In [2]:
list_1 = [1,2,3,4,5]
list1 = np.array(list_1)
list1

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => [[1,2,3],[4,5,6],[7,8,9]]

Convert it into numpy array and print it

In [3]:
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(matrix1)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

[ [1,3,5],

[7,9,11],

[13,15,17] ]

In [4]:
arr= np.arange(1,18,2).reshape(3,3)
arr

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)



In [5]:
arr = np.random.randint(0,10,10)
arr

array([4, 3, 8, 4, 4, 5, 5, 0, 7, 5])

Create numpy array => [1,2,3,4,5] and convert it to 2D array with 5 rows

In [6]:
a = np.array( [1,2,3,4,5])
b = a.reshape(1,5)
b

array([[1, 2, 3, 4, 5]])

Print the shape of the above created array


In [7]:
b.shape

(1, 5)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.



In [8]:
arr2= np.array([1,2,3,4,5,6,7,8,9,10])

In [9]:
arr2[2]

3

In [10]:
arr2[3]

4

In [11]:
arr2[8]

9

Print alternate elements of that array

In [12]:
s = slice(0,10,2)

In [13]:
arr2[s]

array([1, 3, 5, 7, 9])


Change last 3 elements into 100 using broadcasting and print

In [14]:
arr2[7:]=0

In [15]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 0, 0, 0])


Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [16]:
arr3 = np.arange(1,125,5).reshape(5,5)
arr3

array([[  1,   6,  11,  16,  21],
       [ 26,  31,  36,  41,  46],
       [ 51,  56,  61,  66,  71],
       [ 76,  81,  86,  91,  96],
       [101, 106, 111, 116, 121]])

In [17]:
arr3[1:-1,1:-1]

array([[31, 36, 41],
       [56, 61, 66],
       [81, 86, 91]])